This XML file does not appear to have any style information associated with it. The document tree is shown below.
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sch="http://www.generated.com/annonce" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.generated.com/annonce" targetNamespace="http://www.generated.com/annonce">
<wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.generated.com/annonce">
<xs:element name="AnnonceRequest">
<xs:complexType>
<xs:sequence>
<xs:element name="id" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="AnnonceResponse">
<xs:complexType>
<xs:sequence>
<xs:element name="AnnonceDetails" type="tns:AnnonceDetails"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:complexType name="AnnonceDetails">
<xs:sequence>
<xs:element name="id" type="xs:string"/>
<xs:element name="surface" type="xs:string"/>
<xs:element name="roomsNumber" type="xs:string"/>
<xs:element name="location" type="xs:string"/>
<xs:element name="price" type="xs:string"/>
<xs:element name="photoUrl" type="xs:string"/>
<xs:element name="description" type="xs:string"/>
<xs:element name="phoneNumber" type="xs:string"/>
<xs:element name="operation" type="xs:string"/>
<xs:element name="available" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:schema>
</wsdl:types>
<wsdl:message name="AnnonceRequest">
<wsdl:part element="tns:AnnonceRequest" name="AnnonceRequest"> </wsdl:part>
</wsdl:message>
<wsdl:message name="AnnonceResponse">
<wsdl:part element="tns:AnnonceResponse" name="AnnonceResponse"> </wsdl:part>
</wsdl:message>
<wsdl:portType name="AnnoncePort">
<wsdl:operation name="Annonce">
<wsdl:input message="tns:AnnonceRequest" name="AnnonceRequest"> </wsdl:input>
<wsdl:output message="tns:AnnonceResponse" name="AnnonceResponse"> </wsdl:output>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="AnnoncePortSoap11" type="tns:AnnoncePort">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="Annonce">
<soap:operation soapAction=""/>
<wsdl:input name="AnnonceRequest">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="AnnonceResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="AnnoncePortService">
<wsdl:port binding="tns:AnnoncePortSoap11" name="AnnoncePortSoap11">
<soap:address location="http://localhost:8080/ws"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>